language: php

php:
 - 5.6.20

notifications:
 email: false

services:
 - mysql

before_install:
 - mysql -e 'CREATE DATABASE IF NOT EXISTS forex;'

install:
 - composer require --dev phpunit/phpunit ^5.5.21
 - curl -s http://getcomposer.org/installer | php
 - php composer.phar install -n

script: php vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_success: "sbt coveralls"
  - bash <(curl -s https://codecov.io/bash)
  - php vendor/bin/codacycoverage clover build/logs/clover.xml
